### PR TITLE
Add TorrentGalaxy/TGx support

### PR DESCRIPTION
**Pull request by Mr-ROPer**
Hey. I implemented support for TGx :).

### CODE REVIEW

**Comment by Mr-ROPer** [comment]
I'm looking at sites with cloudflare next. [This](https://github.com/VeNoMouS/cloudscraper) looks pretty promising, so I'm going to try some things.

**Comment by X0R0X** [comment]
Cool ! The cloudscraper thingie looks pretty promising, hopefully it won't get broken soon / often.

**Comment by X0R0X** [comment]
Only bad thing is the 5s delay tho :( lets see how usable it gonna be. It would be good to inform the user in some way.

**Comment by Mr-ROPer** [comment]
Agreed. Perhaps we should keep a list of optional trackers that users need to manually enable (e.g. Sukebei), and have a section for engines that communicate with slow servers.

**Pull request merged**
